apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: myapp
    repoURL: <Git Repository URL>
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
